apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.group }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
            env:
            - name: HEAP_SIZE
              value: {{ .Values.heapSize }}
            - name: SPRING_APPLICATION_JSON
              value: >-
                {{- toJson .Values.application | nindent 16 }}
          restartPolicy: OnFailure