logging:
  level:
    root: "INFO"
mongo:
  connectionString: "${MONGODB_CONNECTION_STRING}"
  database: "${MONGODB_DATABASE}"
chargebee:
  mirror:
    baseUrl: "${CHARGEBEE_MIRROR_BASE_URL}"
    password: "${CHARGEBEE_MIRROR_PASSWORD}"