version: v1.0
name: Deploy to Development
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: do-k8s
      env_vars:
        - name: KUBECONFIG
          value: /home/semaphore/.kube/dok8s.yaml
        - name: RELEASE_NAME
          value: premium-synchronizer-development
      jobs:
        - name: Deploy to Kubernetes
          commands:
            - checkout
            - curl -L https://git.io/get_helm.sh | bash
            - helm upgrade $RELEASE_NAME ./chart
                --set image.tag=${SEMAPHORE_GIT_SHA}